name: Java CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY_USER: gayatri589
      
    steps:
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
       
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Perform google formatter check
        run: mvn com.spotify.fmt:fmt-maven-plugin:check

      - name: GitLeaks Scan
        uses: zricethezav/gitleaks-action@v1.3.0
        with:
          args: --path=.

      - name: OSS scan
        run: mvn ossindex:audit

      - name: OWASP Scan
        if: false
        run: mvn org.owasp:dependency-check-maven:check

      - name: Build code and create docker image
        run: mvn clean install docker:build

      - name: Re-tag the Docker image
        run: docker tag dnyanyog.org/api-gateway-hospital:latest ${{ env.DOCKER_REGISTRY_USER }}/api-gateway-hospital:latest

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }} 
       
      - name: Push Docker image
        run: docker push "${{ env.DOCKER_REGISTRY_USER }}/api-gateway-hospital:latest"

  license-finder-check:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: gayatri589/license-finder:latest
      options: --entrypoint ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: /root/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Run License Finder
        run: |
          cd <path_to_your_maven_project>
          license_finder

